# Generated by Django 4.2.7 on 2023-12-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="member",
            table="members",
        ),
    ]
