name: Django CI/CD Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check Python version
        run: python --version
        working-directory: ./app/members
      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: ./app/members
      - name: Run Migrations
        run: python manage.py migrate
        working-directory: ./app/members
      - name: Run Test
        run: python manage.py test
        working-directory: ./app/members
